name: Deploy basic CDK app

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read 

jobs:
  deploy_to_env1:
    name: Deploy to env1
    uses: ./.github/workflows/deployment-job.yaml
    with:
      env: env1
    secrets: inherit

  deploy_to_env2:
    needs: deploy_to_env1
    name: Deploy to env2
    uses: ./.github/workflows/deployment-job.yaml
    with:
      env: env2
    secrets: inherit